version: '3'
services:
  jupyter:
    build: ./
    container_name: myjupyter
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - "8888:8888"
    command: jupyter notebook --notebook-dir /work --ip=0.0.0.0 --allow-root
  binder:
    build:
      context: .
      dockerfile: ./binder/Dockerfile
    container_name: mybinder
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - "8888:8888"
    command: jupyter notebook --notebook-dir /work --ip=0.0.0.0 --allow-root
  julia:
    build: ./
    container_name: myjulia
    volumes:
      - ./:/work
    working_dir: /work
    command: julia --project=/work
  web:
    build: ./
    container_name: mypackagedocs
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - "8000:8000"
    command: make web
