name = "MyWorkflow"
uuid = "7abf360e-92cb-4f35-becd-441c2614658a"
authors = ["Satoshi Terasaki <terasakisatoshi.math@gmail.com>"]
version = "0.2.1"

[deps]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"

[compat]
Example = "= 0.5.1, 0.5"
SymPy = "1.0"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
