version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4-stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: build Docker
          command: |
            docker build -t jltestimage .
      - run:
          name: test julia
          command: |
            echo ${PWD}
            docker run -d --name=tester --rm -it -w /project jltestimage /bin/bash
            docker cp ~/project tester:/
            docker exec tester  \
              julia --project=/project -e '\
              using Pkg; \
              Pkg.test(); \
            '
            docker stop tester

workflows:
  version: 2
  build:
    jobs:
      - build:
          branches:
            ignore: 
              - gh-pages
