name: Build container

on:
  - pull_request

jobs:
  build-container:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: terasakisatoshi
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: terasakisatoshi/myworkflowjl:build
          push_image_and_stages: true
      - name: Build Docker Image
        run: docker build --cache-from terasakisatoshi/myworkflowjl:build -t myworkflowjl .
      - name: Runtime Test   
        run: docker run myworkflowjl julia -e 'using InteractiveUtils; versioninfo()'
